//
// Created by hideoncode on 6/9/20.
//

#include "stage.h"

stage::stage(int whichStage) {
    wallChar = '1';
    immuneWallChar = '2';
    voidChar = ' ';
    switch (whichStage) {
        case 1:
            char stage1[25][25] = {{immuneWallChar, wallChar, wallChar, wallChar, wallChar, wallChar, wallChar, wallChar, wallChar, wallChar, wallChar, wallChar, wallChar, wallChar, wallChar, wallChar, wallChar, wallChar, wallChar, wallChar, wallChar, wallChar, wallChar, wallChar, immuneWallChar},
                                  {wallChar,       voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, wallChar},
                                  {wallChar,       voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, wallChar},
                                  {wallChar,       voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, wallChar},
                                  {wallChar,       voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, wallChar},
                                  {wallChar,       voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, wallChar},
                                  {wallChar,       voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, wallChar},
                                  {wallChar,       voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, wallChar},
                                  {wallChar,       voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, wallChar},
                                  {wallChar,       voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, wallChar},
                                  {wallChar,       voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, wallChar},
                                  {wallChar,       voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, wallChar},
                                  {wallChar,       voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, wallChar},
                                  {wallChar,       voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, wallChar},
                                  {wallChar,       voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, wallChar},
                                  {wallChar,       voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, wallChar},
                                  {wallChar,       voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, wallChar},
                                  {wallChar,       voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, wallChar},
                                  {wallChar,       voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, wallChar},
                                  {wallChar,       voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, wallChar},
                                  {wallChar,       voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, wallChar},
                                  {wallChar,       voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, wallChar},
                                  {wallChar,       voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, wallChar},
                                  {wallChar,       voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, wallChar},
                                  {immuneWallChar, wallChar, wallChar, wallChar, wallChar, wallChar, wallChar, wallChar, wallChar, wallChar, wallChar, wallChar, wallChar, wallChar, wallChar, wallChar, wallChar, wallChar, wallChar, wallChar, wallChar, wallChar, wallChar, wallChar, immuneWallChar}};
        case 2:
            char stage2[30][30] = {{immuneWallChar, wallChar, wallChar, wallChar, wallChar, wallChar, wallChar, wallChar, wallChar, wallChar, wallChar, wallChar, wallChar, wallChar, wallChar, wallChar, wallChar, wallChar, wallChar, wallChar, wallChar, wallChar, wallChar, wallChar, immuneWallChar},
                {wallChar,       voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, wallChar},
                {wallChar,       voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, wallChar},
                {wallChar,       voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, wallChar},
                {wallChar,       voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, wallChar},
                {wallChar,       voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, wallChar},
                {wallChar,       voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, wallChar},
                {wallChar,       voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, wallChar},
                {wallChar,       voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, wallChar},
                {wallChar,       voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, wallChar},
                {wallChar,       voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, wallChar},
                {wallChar,       voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, wallChar},
                {wallChar,       voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, wallChar},
                {wallChar,       voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, wallChar},
                {wallChar,       voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, wallChar},
                {wallChar,       voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, wallChar},
                {wallChar,       voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, wallChar},
                {wallChar,       voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, wallChar},
                {wallChar,       voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, wallChar},
                {wallChar,       voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, wallChar},
                {wallChar,       voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, wallChar},
                {wallChar,       voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, wallChar},
                {wallChar,       voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, wallChar},
                {wallChar,       voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, voidChar, wallChar},
                {immuneWallChar, wallChar, wallChar, wallChar, wallChar, wallChar, wallChar, wallChar, wallChar, wallChar, wallChar, wallChar, wallChar, wallChar, wallChar, wallChar, wallChar, wallChar, wallChar, wallChar, wallChar, wallChar, wallChar, wallChar, immuneWallChar}};
        case 3:
        case 4:
    }
}
